repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/troian/pre-commit-golang
  rev: ab57c5d
  hooks:
    - id: go-fmt
    - id: go-lint
    - id: go-imports
    - id: go-build
